apiVersion: apps/v1
kind: Deployment
metadata:
  name: user11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user11
  template:
    metadata:
      labels:
        app: user11
    spec:
      containers:
        - name: user11-server
          image: ghcr.io/karnwd/kwgit
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user11-service
  labels:
    app: user11-service
spec:
  selector:
    app: user11
  ports:
    - name: web-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP