apiVersion: app/v1
kind: Deployment
metadata:
  name: kwgit-ka
spec:
  replicas: 1
  selecttor:
    matchLabels:
      app: kwgit-ka
  template:
    metadata:
      labels:
        app: kwgit-ka
    spec:
      containers:
        - name: kwgit-server
          image: ghcr.io/karnwd/kwgit
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: karnw-service
  labels:
    app: karnw-service
spec:
  selector:
    app: kwgit-ka
  ports:
    - name: web-port
      protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP

  # 9, 13, 29